LDFLAGS+=-lstack -l queue -L/home/creeper/Desktop/嵌入式/files/datastruct/stack/stack -L/home/creeper/Desktop/嵌入式/files/datastruct/queue/q

ballclock:ballclock.c
	gcc -o $@ $^ $(LDFLAGS)

clean:
	rm *.o ballclock
